name: Build and Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Ejecutará la acción cuando hagas push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Trae el código de tu repositorio

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1  # Prepara Docker para construir imágenes

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1  # Se conecta a Amazon ECR para almacenar imágenes

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }} .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ secrets.ECS_CLUSTER }}
          service: ${{ secrets.ECS_SERVICE }}
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
